### ISSUE TITLE
Solder paste Gerber layer

### ISSUE THREAD

**Issue by pdp7** [TruckHacking/TruckDuckHardware#1]
Hi, I would like to get a stencil made.  Is it possible to get the solder paste Gerber layer?

thanks!
drew

**Comment by sixvolts** [comment]
I added the file truck-duck.gtp which I used to make my stencil. Hopefully that works.

**Comment by pdp7** [comment]
thanks!

**Comment by pdp7** [comment]
@sixvolts I believe we met at Defcon.  I'm happy to do any prototypes you need, just email board size to drew@oshpark.com.  I'm also always interested to get any feedback about the BeagleBone and/or answer questions: drew@beagleboard.org.  Thanks!
